name: Dependabot Auto Build & Merge

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  dependabot-build-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: |
          echo "baseUrl=${{ secrets.BASE_URL }}" > local.properties
          echo "appVersionCode=${{ secrets.APP_VERSION_CODE }}" >> local.properties
          echo "appVersionName=${{ secrets.APP_VERSION_NAME }}" >> local.properties
          ./gradlew assembleDebug --no-daemon

      # Optional: run tests as well
      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Enable automerge for PR
        uses: peter-evans/enable-pull-request-automerge@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
